import Foundation

/// Trims the macOS wallpaper agent's render cache.
///
/// When the app sets a wallpaper, `wallpaper.agent` decodes the source image
/// into one uncompressed `.bmp` per display resolution and stows it under its
/// container's `Caches`. The agent dedupes by content hash but never evicts
/// old entries on its own — only the system's disk-pressure purge reclaims
/// them, and only when the volume is nearly full. A rotator that cycles through
/// hundreds of high-resolution works therefore grows this cache without bound
/// (tens of gigabytes is common).
///
/// This janitor is the app's opt-in bound on that growth: keep the newest
/// renders up to a size cap and delete the oldest `.bmp` files beyond it.
/// Everything it removes is regenerated by the agent on demand, so pruning is
/// safe — at worst the current wallpaper re-renders once.
public struct WallpaperCacheJanitor {
    public struct PruneResult: Equatable {
        public let bytesBefore: Int64
        public let bytesFreed: Int64
        public let filesRemoved: Int

        public var bytesAfter: Int64 { bytesBefore - bytesFreed }
    }

    /// Root of the wallpaper agent's cache. Defaults to the real per-user
    /// location; tests inject a temporary directory.
    public let cacheDirectory: URL

    public init(cacheDirectory: URL = WallpaperCacheJanitor.defaultCacheDirectory()) {
        self.cacheDirectory = cacheDirectory
    }

    public static func defaultCacheDirectory(
        homeDirectory: URL = FileManager.default.homeDirectoryForCurrentUser
    ) -> URL {
        homeDirectory
            .appendingPathComponent("Library/Containers/com.apple.wallpaper.agent")
            .appendingPathComponent("Data/Library/Caches/com.apple.wallpaper.caches")
    }

    /// Total bytes of `.bmp` renders currently cached. Returns 0 if the
    /// directory doesn't exist yet (e.g. no wallpaper ever set).
    public func currentSizeBytes() -> Int64 {
        cachedRenders().reduce(0) { $0 + $1.size }
    }

    /// Delete the oldest cached renders until the total falls to or below
    /// `maxBytes`. A no-op when already under the cap or when the directory is
    /// missing. Files the agent is actively holding open may resist deletion;
    /// those are skipped rather than treated as failures.
    @discardableResult
    public func prune(toMaxBytes maxBytes: Int64) -> PruneResult {
        guard maxBytes >= 0, isSafeToOperateOn(cacheDirectory) else {
            return PruneResult(bytesBefore: 0, bytesFreed: 0, filesRemoved: 0)
        }

        let renders = cachedRenders()
        let total = renders.reduce(0) { $0 + $1.size }
        guard total > maxBytes else {
            return PruneResult(bytesBefore: total, bytesFreed: 0, filesRemoved: 0)
        }

        // Oldest first, so a prune keeps the most recently rendered wallpapers.
        let oldestFirst = renders.sorted { $0.modified < $1.modified }
        var remaining = total
        var freed: Int64 = 0
        var removed = 0
        let fileManager = FileManager.default

        for render in oldestFirst {
            guard remaining > maxBytes else { break }
            do {
                try fileManager.removeItem(at: render.url)
                remaining -= render.size
                freed += render.size
                removed += 1
            } catch {
                // Locked/in-use file — leave it and keep going.
                continue
            }
        }

        return PruneResult(bytesBefore: total, bytesFreed: freed, filesRemoved: removed)
    }

    // MARK: - Internals

    private struct Render {
        let url: URL
        let size: Int64
        let modified: Date
    }

    private func cachedRenders() -> [Render] {
        guard isSafeToOperateOn(cacheDirectory) else { return [] }
        let fileManager = FileManager.default
        let keys: [URLResourceKey] = [.isRegularFileKey, .fileSizeKey, .contentModificationDateKey]
        guard let enumerator = fileManager.enumerator(
            at: cacheDirectory,
            includingPropertiesForKeys: keys,
            options: [.skipsHiddenFiles]
        ) else { return [] }

        var renders: [Render] = []
        for case let url as URL in enumerator {
            guard url.pathExtension.lowercased() == "bmp" else { continue }
            guard let values = try? url.resourceValues(forKeys: Set(keys)),
                  values.isRegularFile == true else { continue }
            let size = Int64(values.fileSize ?? 0)
            let modified = values.contentModificationDate ?? .distantPast
            renders.append(Render(url: url, size: size, modified: modified))
        }
        return renders
    }

    /// Defense-in-depth: only ever touch a path that actually looks like the
    /// wallpaper agent's cache, so a mis-wired URL can't delete something else.
    private func isSafeToOperateOn(_ url: URL) -> Bool {
        let path = url.standardizedFileURL.path
        return path.contains("com.apple.wallpaper.agent")
            && path.contains("Caches")
    }
}
